repos:
  - repo: local
    hooks:
      - id: lint
        name: ansible-lint
        entry: /bin/bash -c "ansible-lint plays/"
        language: script
        types:
          - "yaml"
        pass_filenames: false
